#!/bin/bash

declare -r cmd="$(dmenu_path | dmenu -i $@)"

case $cmd in
    !c ) clipmenu;;
    !m ) dmenu_mpc;;
    *\!) urxvtc -e "$(printf "%s" "${cmd}" | cut -d'!' -f1)";;
    *  ) ${cmd};;
esac
exit

