#!/bin/bash

declare -r cmd="$(dmenu_path | dmenu -i $@)"

case $cmd in
    \:clip  ) clipmenu -p "$(echo -en "\uEAC0 ")";;
    \:dock  ) $HOME/.local/bin/_xutils/set-docked true;;
    \:pass  ) dmenu_pass;;
    \:play  ) dmenu_mpc;;
    \:undock) $HOME/.local/bin/_xutils/set-docked false;;

    \:*) alacritty -e "$(printf "%s" "${cmd}" | cut -d':' -f2)";;
    *\:) alacritty -e "$(printf "%s" "${cmd}" | cut -d':' -f1)";;

    *) ${cmd};;
esac
exit

