#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Implementation adapted from the one in https://github.com/cdown/mpdmenu
#
# The MIT License
#
# Copyright (c) 2013-present Christopher Down
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

declare -r all_text='All'
declare -r artist_text=$(echo -ne "\uF001 ")
declare -r album_text=$(echo -ne "\uE271 ")

function d_artist() {
    mpc list artist | sort -f | dmenu -i -p "$artist_text"
}

function d_album() {
    local artist="$1"
    local albums

    mapfile -t albums < <(mpc list album artist "$artist")
    {
        printf '%s\n' "$all_text"
        printf '%s\n' "${albums[@]}" | sort -f
    } | dmenu -i -p "$album_text"
}

function main() {
    local -r artist=$(d_artist)
    [[ $artist ]] || exit 1

    local -r album=$(d_album "$artist")
    [[ $album ]] || exit 2

    mpc clear
    if [[ $album == "$all_text" ]]; then
        mpc find artist "$artist" | sort | mpc add
    else
        mpc find artist "$artist" album "$album" | sort | mpc add
    fi

    mpc play >/dev/null
}; main $@;
